### ISSUE TITLE
How to build/use this code

### ISSUE THREAD

**Issue by C4RP3N0CT3M** [bizzycola/SLP-Sharp#1]
I'm not sure this is an issue exactly, but I'm curious about how to actually use this code. Can you perhaps add a small tutorial/walk-through in your readme? Thanks in advance for any help you are able to provide.

Edit: Specifically I was wondering how to use this in conjunction with switch-lan-play

**Comment by gut5** [comment]
1. Install VS2019 (Community edition works fine here)
2. Clone github/download the source, open the .sln file in the folder
3. Menu -> Build Solution 
4. To package it for use on a different machine, use "Publish" instead of "Build"

**Comment by bizzycola** [comment]
I've added build instructions for both Visual Studio and the CLI for other platforms/IDEs.
